### ISSUE TITLE
The reference implementation or paper of the MUC metric

### ISSUE THREAD

**Issue by jackfromeast** [LowinLi/metric4coref#1]
Hi~

Appreciate so much for your excellent work! However, since it is quite different from the original paper, [A Model-Theoretic Coreference Scoring Scheme](https://aclanthology.org/M95-1005.pdf), I wonder which implementation or paper did you refer to when realizing the MUC metric? After I checked several test cases, it seems that your implementation of the MUC metric is more critical than the paper I mentioned.

**Comment by LowinLi** [comment]
Sorry for reply late
The MUC metric is interpreted in [Readme.md](https://github.com/LowinLi/metric4coref#%E7%AE%97%E6%B3%95%E8%A7%A3%E8%AF%BB)
This is my comprehension in the paper mentioned
Hope it is accurate :)

**Comment by xiulinyang** [comment]
Hi, I found the same problem too. If I understand MUC correctly, it should calculate the **minimal** number of links missing in the output cluster. According to the example you give in the ```readme``` file and the code, it seems not the case. For example, in a cluster ['a', 'b', 'c'], the minimal number of links to connect all the mentions should be 2 (a-b-c) but it seems you take the connection between 'a' and 'c' as a link, too. Apologies if I misunderstood it.
