### ISSUE TITLE
F1 score error

### ISSUE THREAD

**Issue by xiulinyang** [LowinLi/metric4coref#2]
Hi, thank you for this great tool and the elaborated explanation of those metrics. :)

Just a kind reminder that in the calculation of f1, it is possible for both precision and recall to be zero and thus it might give an error as the denominator might be zero. The same for precision and recall, too. 

Many thanks again!

**Comment by LowinLi** [comment]
Thank you!

I have fixed this problem in code.

**Comment by LowinLi** [comment]
I have committed at the source code
https://github.com/LowinLi/metric4coref/commit/ca843979a66437a4963ad135a0d3bf364dc1c08a
update in pypi version 0.0.2 please.
```
pip install metric4coref==0.0.2
```

**Comment by xiulinyang** [comment]
Thank you for the prompt fix! I'll close the issue.
